version: '3.3'
services:
 mysql:
  image: mysql@sha256:4552fcc5d3cdb8cdee76ee25cce28bf60b0eb3ce93d25ba3bfff7a66bfdcdee8
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  volumes:
    - ./docker-entrypoint-initdb.d/mysql:/docker-entrypoint-initdb.d
  ports:
   - ${MYSQL_PORT:-43306}:3306
  environment:
   - MYSQL_USER=${DB_USER:-user}
   - MYSQL_PASSWORD=${DB_PASSWORD:-password}
   - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
  env_file:
   - ../.env
  healthcheck:
    test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    timeout: 20s
    retries: 10

 postgres:
  image: postgres@sha256:6b841c8f6a819884207402f1209a8116844365df15fca8cf556fc54a24c70800
  restart: always
  volumes:
    - ./docker-entrypoint-initdb.d/postgres:/docker-entrypoint-initdb.d
  ports:
   - ${POSTGRES_PORT:-45432}:5432
  environment:
    - POSTGRES_USER=${DB_USER:-user}
    - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
  env_file:
   - ../.env

 adminer:
  image: adminer@sha256:b75eae89431e8469613b844e76382a26efc8601c17f446bcd81665bc87ca9a1f
  restart: always
  ports:
   - 48080:8080
